### ISSUE TITLE
INFOGRAFÍA

### ISSUE THREAD

**Issue by Litzy-lopez4** [SistemasTecTlaxiaco/actividad-1-infografia-Litzy-lopez4#2]
[INFOGRAFIA CICLO DE VIDA DEL SOFTWARE.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-Litzy-lopez4/files/9435183/INFOGRAFIA.CICLO.DE.VIDA.DEL.SOFTWARE.pdf)

**Comment by IrvingFernand0** [comment]
Calificación: 18.5

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
